server:
  port: 8080

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.4.76.243:3306/simple_robot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 'x'
      validationQueryTimeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

  redis:
    host: 121.4.76.243
    port: 6379
    password: Woaiwojia_22
    database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: simbot.demo.entity
  configuration:
    #控制台输出执行的sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
#在application中修改掉静态文件映射

resources:
  static-locations: classpath:/

simbot:
  core:
    bots: 515438175:....2+2woaiwojia
#    bots: 2793168189:Woaiwojia_22
#    bots: 821309218:....2+2woaiwojia
  component:
    mirai:
      protocol: ANDROID_PAD
#      useSimbotBotLog: false
#      useSimbotNetworkLog: false

# springboot 日志配置.
logging:
  level:
    # 本项目日志debug
    simbot.demo: debug
    # simbot相关内容日志debug
    love.forte.simbot: debug
